platform :ios, '9.0'
pod 'Yoga', path: '../node_modules/react-native/ReactCommon/yoga/Yoga.podspec'
pod 'React', path: '../node_modules/react-native'
pod 'react-native-rtmpview', :path => '../node_modules/react-native-rtmpview'